left_wheel/pid_parameters:
  antiwindup: false
  d: 0.000001
  i: 0.08
  i_clamp_max: 0.1
  i_clamp_min: -0.1
  p: 0.00045
right_wheel/pid_parameters:
  antiwindup: false
  d: 0.000001
  i: 0.08
  i_clamp_max: 0.1
  i_clamp_min: -0.1
  p: 0.00045
